[package]
name = "blip_buf-sys"
version = "0.1.0"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
build = "build.rs"

[lib]
name = "blip_buf_sys"
path = "lib.rs"

[dependencies]
libc = "0.1"

[build-dependencies]
gcc = "0.3"
